In [1]:
import pandas as pd
import json

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [91]:
# Load the Excel file
beverage_list_path = './TCF-Coffe_App-Export_Beverage-List.csv'
impact_data_path = './TCF-Coffe_App-Export_Impact-Data.csv'
sugar_data_path = './TCF-Coffe_App-Export_Sugar-Data.csv'
impact_description_path = './TCF-Coffe_App-Export_Impact-Description.csv'
coffee_description_path = './TCF-Coffe_App-Export_Coffee-Description.csv'

df_beverage_list = pd.read_csv(beverage_list_path,delimiter=';',encoding='windows-1252')
df_impact_data = pd.read_csv(impact_data_path,delimiter=';',encoding='windows-1252')
df_sugar_data = pd.read_csv(sugar_data_path,delimiter=';',encoding='windows-1252')
df_impact_description = pd.read_csv(impact_description_path,delimiter=';',encoding='windows-1252')
df_coffee_description = pd.read_csv(coffee_description_path,delimiter=';',encoding='windows-1252')

df_beverage_list['Labels'] = df_beverage_list['Labels'].str.split(';').str[0]
df_beverage_list['Labels'] = df_beverage_list['Labels'].str.replace(' ', '', regex=False).str.replace(',', '|', regex=False).str.replace('.', '', regex=False)
df_beverage_list['Retail name'] = df_beverage_list['Retail name'] + "\n" + df_beverage_list['Salepoint']

df_beverage_list.head()

,Beverage ID,Retail name,Retail price,Hidden Costs,True Price,Beverage-type,Salepoint,Deca,Milk Type,Price Excluding Tax,Value Added Tax,Smart Value Added Tax,Smart Pricing rounded,Labels
0,"Café Blue Planet, Dallmayr",Café Blue Planet\nDallmayr,1.7,-0.014,1.69,Café,Dallmayr,False,none,1.573,0.127,0.025,1.60,blue-planet|fairtrade|eu-organic
1,"Café Macchiato Blue Planet, Dallmayr",Café Macchiato Blue Planet\nDallmayr,1.8,0.041,1.84,Café Macchiato,Dallmayr,False,none,1.665,0.135,0.030,1.70,blue-planet|fairtrade|eu-organic
2,"Café Macchiato Via Verde, Dallmayr",Café Macchiato Via Verde\nDallmayr,1.7,0.148,1.85,Café Macchiato,Dallmayr,False,none,1.573,0.127,0.040,1.65,via-verde|fairtrade|eu-organic
3,"Café Via Verde, Dallmayr",Café Via Verde\nDallmayr,1.6,0.094,1.69,Café,Dallmayr,False,none,1.480,0.120,0.035,1.55,via-verde|fairtrade|eu-organic
4,"Café, Compass Machine",Café Via Verde\nCompass Machine,1.5,0.094,1.59,Café,Compass Machine,False,none,1.388,0.112,0.035,1.45,via-verde|fairtrade|eu-organic

In [11]:

duplicate_rows = df_impact_data.groupby(by=["Beverage ID", "Ingredient", "Impact Category", "Stage", "Indicator"]).filter(lambda x: len(x) >= 2)
duplicate_rows = duplicate_rows.sort_values(by=["Beverage ID", "Ingredient", "Impact Category", "Stage", "Indicator"])
duplicate_rows.to_csv('duplicate_rows.csv',index=False)

In [10]:
duplicate_rows

,Beverage ID,Ingredient,Stage,Impact Category,Indicator,Unit,Monetary Value,Value,References
26295,"Café Blue Planet, Dallmayr",Coffee beans,Offsetting schemes,Biodiversity,Biodiversity restoration through Reforestation...,m²/kg,0.0,0.0,"Fairtrade regulation, No specific regulation e..."
26297,"Café Blue Planet, Dallmayr",Coffee beans,Offsetting schemes,Biodiversity,Biodiversity restoration through Reforestation...,m²/kg,0.0,0.0,"EU-organic standards, No specific regulation o..."
26457,"Café Blue Planet, Dallmayr",Coffee beans,Offsetting schemes,Biodiversity,Biodiversity restoration through Reforestation...,m²/kg,0.0,0.0,"Fairtrade regulation, No specific regulation e..."
26459,"Café Blue Planet, Dallmayr",Coffee beans,Offsetting schemes,Biodiversity,Biodiversity restoration through Reforestation...,m²/kg,0.0,0.0,"EU-organic standards, No specific regulation o..."
26655,"Café Blue Planet, Dallmayr",Coffee beans,Offsetting schemes,Biodiversity,Biodiversity restoration through Reforestation...,m²/kg,0.0,0.0,"Fairtrade regulation, No specific regulation e..."
...,...,...,...,...,...,...,...,...,...
33399,"Ristretto, Le Klee",Coffee beans,Consumption,Health,Thiamethoxam,mg/kg,0.0,0.0,Sustainability Impact Metrics (a spin-off of D...
33596,"Ristretto, Le Klee",Coffee beans,Consumption,Health,Thiamethoxam,mg/kg,0.0,0.0,Sustainability Impact Metrics (a spin-off of D...
33597,"Ristretto, Le Klee",Coffee beans,Consumption,Health,Thiamethoxam,mg/kg,0.0,0.0,Sustainability Impact Metrics (a spin-off of D...
33758,"Ristretto, Le Klee",Coffee beans,Consumption,Health,Thiamethoxam,mg/kg,0.0,0.0,Sustainability Impact Metrics (a spin-off of D...
33759,"Ristretto, Le Klee",Coffee beans,Consumption,Health,Thiamethoxam,mg/kg,0.0,0.0,Sustainability Impact Metrics (a spin-off of D...

In [92]:
def get_indicator_values(row):

    # # Find matches where df_impact_description['Indicator'] is contained in row['Indicator']
    # matched_rows = df_impact_description[
    #     df_impact_description['Indicator'].apply(lambda x: x in row['Indicator'])
    # ]
    
    # if matched_rows.empty:
    #     impact_definition = None
    #     monetisation_method = None
    # else:
    #     # Select the most specific match (longest string in df_impact_description['Indicator'])
    #     impact_definition = matched_rows.loc[matched_rows['Indicator'].str.len().idxmax(), 'Indicator definition']
    #     monetisation_method = matched_rows.loc[matched_rows['Indicator'].str.len().idxmax(), 'Monetisation method']
    
    return {
        'indicators': row['Indicator'],
        'unit': row['Unit'],
        'impactValue': row['Value'], 
        'costValue': row['Monetary Value'], 
        # 'impactDefinition': impact_definition,
        # 'monetisationMethod': monetisation_method,
        'reference': None if pd.isna(row['References']) else row['References']
    }


def calculate_impacts(group):
    # Group by stage and impact-category
    grouped_impacts = group.groupby(['Ingredient','Stage', 'Impact Category']).apply(lambda x: {
        'stage': x.iloc[0]['Stage'],
        'ingredient': x.iloc[0]['Ingredient'],
        'impactCategory': x.iloc[0]['Impact Category'],
        'impactValue': x['Value'].sum(),   # Sum impact values
        'costValue': x['Monetary Value'].sum(),   # Sum cost values
        'details': x.apply(get_indicator_values, axis=1).tolist()
    }).reset_index(drop=True).tolist()

    return grouped_impacts

In [83]:
df_beverage_list.head()

,Beverage ID,Retail name,Retail price,Hidden Costs,True Price,Beverage-type,Salepoint,Deca,Milk Type,Price Excluding Tax,Value Added Tax,Smart Value Added Tax,Smart Pricing rounded,Labels
0,"Café Blue Planet, Dallmayr",Café Blue PlanetDallmayr,1.7,-0.014,1.69,Café,Dallmayr,False,none,1.573,0.127,0.025,1.60,blue-planet|fairtrade|eu-organic
1,"Café Macchiato Blue Planet, Dallmayr",Café Macchiato Blue PlanetDallmayr,1.8,0.041,1.84,Café Macchiato,Dallmayr,False,none,1.665,0.135,0.030,1.70,blue-planet|fairtrade|eu-organic
2,"Café Macchiato Via Verde, Dallmayr",Café Macchiato Via VerdeDallmayr,1.7,0.148,1.85,Café Macchiato,Dallmayr,False,none,1.573,0.127,0.040,1.65,via-verde|fairtrade|eu-organic
3,"Café Via Verde, Dallmayr",Café Via VerdeDallmayr,1.6,0.094,1.69,Café,Dallmayr,False,none,1.480,0.120,0.035,1.55,via-verde|fairtrade|eu-organic
4,"Café, Compass Machine",Café Via VerdeCompass Machine,1.5,0.094,1.59,Café,Compass Machine,False,none,1.388,0.112,0.035,1.45,via-verde|fairtrade|eu-organic

In [93]:
# Transform the data
import os
import re


formatted_data = []

i = 0;

# milk_beverage_lists = ['Cappuccino',"Chocolait","Latte Macchiato","Macchiato","Mocaccino", 'Renversé']

for _, beverage in df_beverage_list.iterrows():
    beverage_id = beverage['Beverage ID']
    retail_name = beverage['Retail name']

    # all_removals = labels_list + ['décaféiné', "lait d'amande", "lait d'avoine", "lait de soja", "sans-lactose"]

    # recipe_id_pattern = r'(' + '|'.join(map(re.escape, all_removals)) + r')'
    # recipe_id = re.sub(recipe_id_pattern, '', retail_name, flags=re.IGNORECASE).replace(',','').strip()
    recipe_id = beverage['Beverage-type']
    # sale_point_id = sale_point_mapping[beverage['Salepoint']]
    # is_decaf = 'décaféiné' in beverage['Retail name'].lower()
    is_decaf = beverage['Deca']
    # has_milk = any(x in beverage['Retail name'] for x in milk_beverage_lists)

    # Determine the type of milk, if present
    # milk_types = {'lait d\'amande': 'Almond', 'lait d\'avoine': 'Oat', 'lait de soja': 'Soy', 'sans-lactose': 'Lactose-Free'}
    # milk_type = None
    # for key, value in milk_types.items():
    #     if key in beverage['Retail name'].lower():
    #         milk_type = value
    #         break
    # milk_type = milk_type if milk_type else 'Dairy' if any(x in beverage['Retail name'].lower() for x in ['milk', 'latte', 'cappuccino', 'renversé']) else None
        
    milk_type = beverage['Milk Type']
    has_milk = milk_type != 'none'

    definition_row = df_coffee_description[df_coffee_description['Recipe'] == recipe_id]
    definition = definition_row['Definition'].iloc[0] if not definition_row.empty else ""


    impact_rows = df_impact_data[df_impact_data['Beverage ID'] == beverage_id]
    # print(impact_rows)
    ingredient_list = impact_rows['Ingredient'].unique().tolist()



    grouped_impacts = calculate_impacts(impact_rows)

    path_impacts = './results/impacts/'+beverage_id.lower().replace(' ','_').replace(',','')+'.json'
    os.makedirs(os.path.dirname(path_impacts), exist_ok=True)
    with open(path_impacts, 'w', encoding='utf-8') as f:
        json.dump(grouped_impacts, f, indent=4, ensure_ascii=False)



    formatted_data.append({
        'serveId': beverage_id,
        'recipeId': recipe_id,
        'retailName': retail_name,
        'retailPrice': beverage['Retail price'],
        'hiddenCost': beverage['Hidden Costs'],
        'truePrice': beverage['True Price'],
        'labels': beverage['Labels'],
        'isDecaf': is_decaf,
        'hasMilk': has_milk,
        'milkType': milk_type,
        'coffeeDetails': definition, 

    })

# Create the formatted DataFrame
formatted_df = pd.DataFrame(formatted_data)

# Save to CSV
output_path = './results/coffee_data.csv'
formatted_df.to_csv(output_path, index=False)



print(f"Formatted data saved to {output_path}")

Formatted data saved to ./results/coffee_data.csv

In [94]:

list_sugars = ["Swiss sugar default","Swiss sugar low","Swiss sugar moderate","Swiss sugar high"]

for sugar in list_sugars:
    sugar_rows = df_sugar_data[df_sugar_data['Beverage ID'] == sugar]
    print(sugar_rows)

    grouped_impacts = calculate_impacts(sugar_rows)

    path_impacts = './results/sugar/'+sugar.lower().replace(' ','_').replace(',','')+'.json'
    os.makedirs(os.path.dirname(path_impacts), exist_ok=True)
    with open(path_impacts, 'w', encoding='utf-8') as f:
        json.dump(grouped_impacts, f, indent=4, ensure_ascii=False)

             Beverage ID      Country Ingredient Labels        Stage  \
0    Swiss sugar default  Switzerland  Sugarbeet   none   Production
1    Swiss sugar default  Switzerland  Sugarbeet   none   Production
2    Swiss sugar default  Switzerland  Sugarbeet   none   Production
3    Swiss sugar default  Switzerland  Sugarbeet   none   Production
4    Swiss sugar default  Switzerland  Sugarbeet   none   Production
..                   ...          ...        ...    ...          ...
195  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
196  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
197  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
198  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
199  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  Value  \
0       Environment  Fine particulate matter formation  kg PM2.5 eq    0.0
1       Environment           Fossil resource scarcity    kg oil eq    0.0
2       Environment             Freshwater ecotoxicity   kg 1,4-DCB    0.0
3       Environment          Freshwater eutrophication      kg P eq    0.0
4       Environment                     Global warming    kg CO2 eq    0.0
..              ...                                ...          ...    ...
195          Health                     Pyraclostrobin        mg/kg    0.0
196          Health                       Saflufenacil        mg/kg    0.0
197          Health                       Tebufenozide        mg/kg    0.0
198          Health                      Teflubenzuron        mg/kg    0.0
199          Health                   Trinexapac-Ethyl        mg/kg    0.0

     Monetary Value  ...     Salepoint   Deca Milk Type  Price Excluding Tax  \
0               0.0  ...  Rolex Centre  False      none                    0
1               0.0  ...  Rolex Centre  False      none                    0
2               0.0  ...  Rolex Centre  False      none                    0
3               0.0  ...  Rolex Centre  False      none                    0
4               0.0  ...  Rolex Centre  False      none                    0
..              ...  ...           ...    ...       ...                  ...
195             0.0  ...  Rolex Centre  False      none                    0
196             0.0  ...  Rolex Centre  False      none                    0
197             0.0  ...  Rolex Centre  False      none                    0
198             0.0  ...  Rolex Centre  False      none                    0
199             0.0  ...  Rolex Centre  False      none                    0

    Value Added Tax  Smart Value Added Tax Smart Pricing  \
0                 0                  0.026             0
1                 0                  0.026             0
2                 0                  0.026             0
3                 0                  0.026             0
4                 0                  0.026             0
..              ...                    ...           ...
195               0                  0.026             0
196               0                  0.026             0
197               0                  0.026             0
198               0                  0.026             0
199               0                  0.026             0

    Smart Pricing rounded  Value Unit  \
0                       0  USD2023/kg
1                       0  USD2023/kg
2                       0  USD2023/kg
3                       0  USD2023/kg
4                       0  USD2023/kg
..                    ...         ...
195                     0  USD2023/mg
196                     0  USD2023/mg
197                     0  USD2023/mg
198                     0  USD2023/mg
199                     0  USD2023/mg

                                            References
0    Sugar beet {CH}| production | Cut-off, S - Cop...
1    Sugar beet {CH}| production | Cut-off, S - Cop...
2    Sugar beet {CH}| production | Cut-off, S - Cop...
3    Sugar beet {CH}| production | Cut-off, S - Cop...
4    Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
195  Food and Agriculture Organisation, World Healt...
196  Food and Agriculture Organisation, World Healt...
197  Food and Agriculture Organisation, World Healt...
198  Food and Agriculture Organisation, World Healt...
199  Food and Agriculture Organisation, World Healt...

[200 rows x 28 columns]
         Beverage ID      Country Ingredient Labels        Stage  \
400  Swiss sugar low  Switzerland  Sugarbeet   none   Production
401  Swiss sugar low  Switzerland  Sugarbeet   none   Production
402  Swiss sugar low  Switzerland  Sugarbeet   none   Production
403  Swiss sugar low  Switzerland  Sugarbeet   none   Production
404  Swiss sugar low  Switzerland  Sugarbeet   none   Production
..               ...          ...        ...    ...          ...
595  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
596  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
597  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
598  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
599  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  \
400     Environment  Fine particulate matter formation  kg PM2.5 eq
401     Environment           Fossil resource scarcity    kg oil eq
402     Environment             Freshwater ecotoxicity   kg 1,4-DCB
403     Environment          Freshwater eutrophication      kg P eq
404     Environment                     Global warming    kg CO2 eq
..              ...                                ...          ...
595          Health                     Pyraclostrobin        mg/kg
596          Health                       Saflufenacil        mg/kg
597          Health                       Tebufenozide        mg/kg
598          Health                      Teflubenzuron        mg/kg
599          Health                   Trinexapac-Ethyl        mg/kg

            Value  Monetary Value  ...     Salepoint   Deca Milk Type  \
400  8.193605e-07    8.822059e-05  ...  Rolex Centre  False      none
401  4.492133e-05    2.375131e-05  ...  Rolex Centre  False      none
402  5.255285e-06    2.518892e-07  ...  Rolex Centre  False      none
403  9.091564e-08    2.184047e-05  ...  Rolex Centre  False      none
404  3.811263e-04    7.140582e-05  ...  Rolex Centre  False      none
..            ...             ...  ...           ...    ...       ...
595  1.200000e-04    1.156332e-06  ...  Rolex Centre  False      none
596  4.500000e-05    0.000000e+00  ...  Rolex Centre  False      none
597  1.500000e-03    8.603664e-06  ...  Rolex Centre  False      none
598  1.500000e-05    1.479830e-06  ...  Rolex Centre  False      none
599  7.500000e-04    0.000000e+00  ...  Rolex Centre  False      none

     Price Excluding Tax Value Added Tax  Smart Value Added Tax Smart Pricing  \
400                    0               0               0.026122             0
401                    0               0               0.026122             0
402                    0               0               0.026122             0
403                    0               0               0.026122             0
404                    0               0               0.026122             0
..                   ...             ...                    ...           ...
595                    0               0               0.026122             0
596                    0               0               0.026122             0
597                    0               0               0.026122             0
598                    0               0               0.026122             0
599                    0               0               0.026122             0

    Smart Pricing rounded  Value Unit  \
400                     0  USD2023/kg
401                     0  USD2023/kg
402                     0  USD2023/kg
403                     0  USD2023/kg
404                     0  USD2023/kg
..                    ...         ...
595                     0  USD2023/mg
596                     0  USD2023/mg
597                     0  USD2023/mg
598                     0  USD2023/mg
599                     0  USD2023/mg

                                            References
400  Sugar beet {CH}| production | Cut-off, S - Cop...
401  Sugar beet {CH}| production | Cut-off, S - Cop...
402  Sugar beet {CH}| production | Cut-off, S - Cop...
403  Sugar beet {CH}| production | Cut-off, S - Cop...
404  Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
595  Food and Agriculture Organisation, World Healt...
596  Food and Agriculture Organisation, World Healt...
597  Food and Agriculture Organisation, World Healt...
598  Food and Agriculture Organisation, World Healt...
599  Food and Agriculture Organisation, World Healt...

[200 rows x 28 columns]
              Beverage ID      Country Ingredient Labels        Stage  \
600  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
601  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
602  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
603  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
604  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
..                    ...          ...        ...    ...          ...
795  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
796  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
797  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
798  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
799  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  \
600     Environment  Fine particulate matter formation  kg PM2.5 eq
601     Environment           Fossil resource scarcity    kg oil eq
602     Environment             Freshwater ecotoxicity   kg 1,4-DCB
603     Environment          Freshwater eutrophication      kg P eq
604     Environment                     Global warming    kg CO2 eq
..              ...                                ...          ...
795          Health                     Pyraclostrobin        mg/kg
796          Health                       Saflufenacil        mg/kg
797          Health                       Tebufenozide        mg/kg
798          Health                      Teflubenzuron        mg/kg
799          Health                   Trinexapac-Ethyl        mg/kg

            Value  Monetary Value  ...     Salepoint   Deca Milk Type  \
600  1.638721e-06    1.764412e-04  ...  Rolex Centre  False      none
601  8.984266e-05    4.750262e-05  ...  Rolex Centre  False      none
602  1.051057e-05    5.037783e-07  ...  Rolex Centre  False      none
603  1.818313e-07    4.368094e-05  ...  Rolex Centre  False      none
604  7.622526e-04    1.428116e-04  ...  Rolex Centre  False      none
..            ...             ...  ...           ...    ...       ...
795  2.400000e-04    2.312665e-06  ...  Rolex Centre  False      none
796  9.000000e-05    0.000000e+00  ...  Rolex Centre  False      none
797  3.000000e-03    1.720733e-05  ...  Rolex Centre  False      none
798  3.000000e-05    2.959660e-06  ...  Rolex Centre  False      none
799  1.500000e-03    0.000000e+00  ...  Rolex Centre  False      none

     Price Excluding Tax Value Added Tax  Smart Value Added Tax Smart Pricing  \
600                    0               0               0.026243             0
601                    0               0               0.026243             0
602                    0               0               0.026243             0
603                    0               0               0.026243             0
604                    0               0               0.026243             0
..                   ...             ...                    ...           ...
795                    0               0               0.026243             0
796                    0               0               0.026243             0
797                    0               0               0.026243             0
798                    0               0               0.026243             0
799                    0               0               0.026243             0

    Smart Pricing rounded  Value Unit  \
600                     0  USD2023/kg
601                     0  USD2023/kg
602                     0  USD2023/kg
603                     0  USD2023/kg
604                     0  USD2023/kg
..                    ...         ...
795                     0  USD2023/mg
796                     0  USD2023/mg
797                     0  USD2023/mg
798                     0  USD2023/mg
799                     0  USD2023/mg

                                            References
600  Sugar beet {CH}| production | Cut-off, S - Cop...
601  Sugar beet {CH}| production | Cut-off, S - Cop...
602  Sugar beet {CH}| production | Cut-off, S - Cop...
603  Sugar beet {CH}| production | Cut-off, S - Cop...
604  Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
795  Food and Agriculture Organisation, World Healt...
796  Food and Agriculture Organisation, World Healt...
797  Food and Agriculture Organisation, World Healt...
798  Food and Agriculture Organisation, World Healt...
799  Food and Agriculture Organisation, World Healt...

[200 rows x 28 columns]
          Beverage ID      Country Ingredient Labels        Stage  \
200  Swiss sugar high  Switzerland  Sugarbeet   none   Production
201  Swiss sugar high  Switzerland  Sugarbeet   none   Production
202  Swiss sugar high  Switzerland  Sugarbeet   none   Production
203  Swiss sugar high  Switzerland  Sugarbeet   none   Production
204  Swiss sugar high  Switzerland  Sugarbeet   none   Production
..                ...          ...        ...    ...          ...
395  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
396  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
397  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
398  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
399  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  \
200     Environment  Fine particulate matter formation  kg PM2.5 eq
201     Environment           Fossil resource scarcity    kg oil eq
202     Environment             Freshwater ecotoxicity   kg 1,4-DCB
203     Environment          Freshwater eutrophication      kg P eq
204     Environment                     Global warming    kg CO2 eq
..              ...                                ...          ...
395          Health                     Pyraclostrobin        mg/kg
396          Health                       Saflufenacil        mg/kg
397          Health                       Tebufenozide        mg/kg
398          Health                      Teflubenzuron        mg/kg
399          Health                   Trinexapac-Ethyl        mg/kg

            Value  Monetary Value  ...     Salepoint   Deca Milk Type  \
200  2.458082e-06    2.646618e-04  ...  Rolex Centre  False      none
201  1.347640e-04    7.125393e-05  ...  Rolex Centre  False      none
202  1.576586e-05    7.556675e-07  ...  Rolex Centre  False      none
203  2.727469e-07    6.552142e-05  ...  Rolex Centre  False      none
204  1.143379e-03    2.142175e-04  ...  Rolex Centre  False      none
..            ...             ...  ...           ...    ...       ...
395  3.600000e-04    3.468997e-06  ...  Rolex Centre  False      none
396  1.350000e-04    0.000000e+00  ...  Rolex Centre  False      none
397  4.500000e-03    2.581099e-05  ...  Rolex Centre  False      none
398  4.500000e-05    4.439491e-06  ...  Rolex Centre  False      none
399  2.250000e-03    0.000000e+00  ...  Rolex Centre  False      none

     Price Excluding Tax Value Added Tax  Smart Value Added Tax Smart Pricing  \
200                    0               0               0.026365             0
201                    0               0               0.026365             0
202                    0               0               0.026365             0
203                    0               0               0.026365             0
204                    0               0               0.026365             0
..                   ...             ...                    ...           ...
395                    0               0               0.026365             0
396                    0               0               0.026365             0
397                    0               0               0.026365             0
398                    0               0               0.026365             0
399                    0               0               0.026365             0

    Smart Pricing rounded  Value Unit  \
200                     0  USD2023/kg
201                     0  USD2023/kg
202                     0  USD2023/kg
203                     0  USD2023/kg
204                     0  USD2023/kg
..                    ...         ...
395                     0  USD2023/mg
396                     0  USD2023/mg
397                     0  USD2023/mg
398                     0  USD2023/mg
399                     0  USD2023/mg

                                            References
200  Sugar beet {CH}| production | Cut-off, S - Cop...
201  Sugar beet {CH}| production | Cut-off, S - Cop...
202  Sugar beet {CH}| production | Cut-off, S - Cop...
203  Sugar beet {CH}| production | Cut-off, S - Cop...
204  Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
395  Food and Agriculture Organisation, World Healt...
396  Food and Agriculture Organisation, World Healt...
397  Food and Agriculture Organisation, World Healt...
398  Food and Agriculture Organisation, World Healt...
399  Food and Agriculture Organisation, World Healt...

[200 rows x 28 columns]

In [95]:
output_path= "./results/impacts_definitions.csv"
df_impact_description.to_csv(output_path, index=False)

In [96]:
import shutil

source_dir = './results/'
destination_dir = '../public/data/'

# Copy the contents of the source directory to the destination directory
shutil.copytree(source_dir, destination_dir, dirs_exist_ok=True)

print(f"Contents of {source_dir} copied to {destination_dir}")

Contents of ./results/ copied to ../public/data/