In [1]:
import pandas as pd
import json
import shutil
import os

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Load the Excel file
beverage_list_path = './TCF-Coffe_App-Export_Beverage-List.csv'
impact_data_path = './TCF-Coffe_App-Export_Impact-Data.csv'
sugar_data_path = './TCF-Coffe_App-Export_Sugar-Data.csv'
impact_description_path = './TCF-Coffe_App-Export_Impact-Description.csv'
coffee_description_path = './TCF-Coffe_App-Export_Coffee-Description.csv'

df_beverage_list = pd.read_csv(beverage_list_path,delimiter=';',encoding='windows-1252')
df_impact_data = pd.read_csv(impact_data_path,delimiter=';',encoding='windows-1252')
df_sugar_data = pd.read_csv(sugar_data_path,delimiter=';',encoding='windows-1252')
df_impact_description = pd.read_csv(impact_description_path,delimiter=';',encoding='windows-1252')
df_coffee_description = pd.read_csv(coffee_description_path,delimiter=';',encoding='windows-1252')

# df_beverage_list['Labels'] = df_beverage_list['Labels'].str.split(';').str[0]
# df_beverage_list['Labels'] = df_beverage_list['Labels'].str.replace(' ', '', regex=False).str.replace(',', '|', regex=False)
df_beverage_list['Retail name'] = df_beverage_list['Retail name'] + " " + df_beverage_list['Salepoint']

df_beverage_list

,Beverage ID,Retail name,Retail price,Hidden Costs,True Price,Net Hidden Costs,Beverage-type,Salepoint,Deca,Milk Type,Price Excluding Tax,Value Added Tax,Smart Value Added Tax,Smart Pricing rounded,Offsetting,Labels
0,"Café Blue Planet, Dallmayr",Café Blue Planet Dallmayr,1.7,0.237,1.67,-0.025,Café,Dallmayr,False,none,1.573,0.127,0.023,1.60,-0.262,blue-planet|fairtrade|eu-organic
1,"Café Macchiato Blue Planet, Dallmayr",Café Macchiato Blue Planet Dallmayr,1.8,0.291,1.83,0.029,Café Macchiato,Dallmayr,False,none,1.665,0.135,0.029,1.70,-0.262,blue-planet|fairtrade|eu-organic
2,"Café Macchiato Via Verde, Dallmayr",Café Macchiato Via Verde Dallmayr,1.7,0.248,1.82,0.120,Café Macchiato,Dallmayr,False,none,1.573,0.127,0.039,1.65,-0.129,via-verde|fairtrade|eu-organic
3,"Café Via Verde, Dallmayr",Café Via Verde Dallmayr,1.6,0.194,1.67,0.065,Café,Dallmayr,False,none,1.480,0.120,0.033,1.55,-0.129,via-verde|fairtrade|eu-organic
4,"Café, Compass Machine",Café Via Verde Compass Machine,1.5,0.194,1.57,0.065,Café,Compass Machine,False,none,1.388,0.112,0.033,1.45,-0.129,via-verde|fairtrade|eu-organic
5,"Café, Le Klee",Café Via Verde Le Klee,1.6,0.194,1.67,0.065,Café,Le Klee,False,none,1.480,0.120,0.033,1.55,-0.129,via-verde|fairtrade|eu-organic
6,"Cappuccino Blue Planet, Dallmayr",Cappuccino Blue Planet Dallmayr,1.8,0.301,1.84,0.039,Cappuccino,Dallmayr,False,Cow milk,1.665,0.135,0.030,1.70,-0.262,blue-planet|fairtrade|eu-organic
7,"Cappuccino Vanille Blue Planet, Dallmayr",Cappuccino Vanille Blue Planet Dallmayr,1.8,0.356,1.89,0.093,Cappuccino,Dallmayr,False,Cow milk,1.665,0.135,0.036,1.70,-0.262,blue-planet|fairtrade|eu-organic
8,"Cappuccino Vanille Via Verde, Dallmayr",Cappuccino Vanille Via Verde Dallmayr,1.7,0.313,1.88,0.184,Cappuccino,Dallmayr,False,Cow milk,1.573,0.127,0.045,1.65,-0.129,via-verde|fairtrade|eu-organic
9,"Cappuccino Via Verde, Dallmayr",Cappuccino Via Verde Dallmayr,1.7,0.258,1.83,0.130,Cappuccino,Dallmayr,False,Cow milk,1.573,0.127,0.040,1.65,-0.129,via-verde|fairtrade|eu-organic
10,"Cappuccino, Compass Machine",Cappuccino Via Verde Compass Machine,2.2,0.258,2.33,0.130,Cappuccino,Compass Machine,False,Cow milk,2.035,0.165,0.040,2.10,-0.129,via-verde|fairtrade|eu-organic
11,"Cappuccino, Le Klee",Cappuccino Via Verde Le Klee,2.7,0.338,2.91,0.209,Cappuccino,Le Klee,False,Cow milk,2.498,0.202,0.048,2.60,-0.129,via-verde|fairtrade|eu-organic
12,"Cappuccino, lait d'amande, Le Klee",Cappuccino Via Verde Le Klee,2.7,0.346,2.92,0.217,Cappuccino,Le Klee,False,Almond milk,2.498,0.202,0.049,2.60,-0.129,via-verde|fairtrade|eu-organic
13,"Cappuccino, lait d'avoine, Le Klee",Cappuccino Via Verde Le Klee,2.7,0.240,2.81,0.111,Cappuccino,Le Klee,False,Oat milk,2.498,0.202,0.038,2.60,-0.129,via-verde|fairtrade|eu-organic|eu-organic
14,"Cappuccino, lait de soja, Le Klee",Cappuccino Via Verde Le Klee,2.7,0.376,2.95,0.248,Cappuccino,Le Klee,False,Soya milk,2.498,0.202,0.052,2.65,-0.129,via-verde|fairtrade|eu-organic
15,"Cappuccino, sans-lactose, Le Klee",Cappuccino Via Verde Le Klee,2.7,0.338,2.91,0.209,Cappuccino,Le Klee,False,Cow milk,2.498,0.202,0.048,2.60,-0.129,via-verde|fairtrade|eu-organic
16,"Chocolait, Dallmayr",Chocolait Dallmayr,1.7,0.369,2.07,0.369,Chocolait,Dallmayr,False,Cow milk,1.573,0.127,0.065,1.65,0.000,rainforest-alliance
17,"Chocolat, Dallmayr",Chocolat Dallmayr,1.6,0.290,1.89,0.290,Chocolat,Dallmayr,False,none,1.480,0.120,0.057,1.55,0.000,rainforest-alliance
18,"Espresso Blue Planet, Dallmayr",Espresso Blue Planet Dallmayr,1.7,0.237,1.67,-0.025,Espresso,Dallmayr,False,none,1.573,0.127,0.023,1.60,-0.262,blue-planet|fairtrade|eu-organic
19,"Espresso Macchiato Blue Planet, Dallmayr",Espresso Macchiato Blue Planet Dallmayr,1.8,0.286,1.82,0.024,Espresso Macchiato,Dallmayr,False,none,1.665,0.135,0.029,1.70,-0.262,blue-planet|fairtrade|eu-organic
20,"Espresso Macchiato Via Verde, Dallmayr",Espresso Macchiato Via Verde Dallmayr,1.7,0.243,1.81,0.115,Espresso Macchiato,Dallmayr,False,none,1.573,0.127,0.038,1.65,-0.129,via-verde|fairtrade|eu-organic
21,"Espresso Via Verde, Dallmayr",Espresso Via Verde Dallmayr,1.6,0.194,1.67,0.065,Espresso,Dallmayr,False,none,1.480,0.120,0.033,1.55,-0.129,via-verde|fairtrade|eu-organic
22,"Espresso, Compass Machine",Espresso Via Verde Compass Machine,1.5,0.194,1.57,0.065,Espresso,Compass Machine,False,none,1.388,0.112,0.033,1.45,-0.129,via-verde|fairtrade|eu-organic
23,"Espresso, Le Klee",Espresso Via Verde Le Klee,1.6,0.194,1.67,0.065,Espresso,Le Klee,False,none,1.480,0.120,0.033,1.55,-0.129,via-verde|fairtrade|eu-organic
24,"Frappé Vanille, Dallmayr",Frappé Vanille Dallmayr,1.7,0.198,1.90,0.198,Frappé,Dallmayr,False,Cow milk,1.573,0.127,0.047,1.65,0.000,none
25,"Latte Macchiato Blue Planet, Dallmayr",Latte Macchiato Blue Planet Dallmayr,1.8,0.331,1.87,0.069,Latte Macchiato,Dallmayr,False,Cow milk,1.665,0.135,0.033,1.70,-0.262,blue-planet|fairtrade|eu-organic
26,"Latte Macchiato Vanille Blue Planet, Dallmayr",Latte Macchiato Vanille Blue Planet Dallmayr,1.8,0.365,1.90,0.103,Latte Macchiato,Dallmayr,False,Cow milk,1.665,0.135,0.037,1.75,-0.262,blue-planet|fairtrade|eu-organic
27,"Latte Macchiato Vanille Via Verde, Dallmayr",Latte Macchiato Vanille Via Verde Dallmayr,1.7,0.322,1.89,0.194,Latte Macchiato,Dallmayr,False,Cow milk,1.573,0.127,0.047,1.65,-0.129,via-verde|fairtrade|eu-organic
28,"Latte Macchiato Via Verde, Dallmayr",Latte Macchiato Via Verde Dallmayr,1.7,0.288,1.86,0.159,Latte Macchiato,Dallmayr,False,Cow milk,1.573,0.127,0.043,1.65,-0.129,via-verde|fairtrade|eu-organic
29,"Latte Macchiato, Le Klee",Latte Macchiato Via Verde Le Klee,2.7,0.374,2.95,0.245,Latte Macchiato,Le Klee,False,Cow milk,2.498,0.202,0.052,2.65,-0.129,via-verde|fairtrade|eu-organic
30,"Latte Macchiato, lait d'amande, Le Klee",Latte Macchiato Via Verde Le Klee,2.7,0.384,2.96,0.255,Latte Macchiato,Le Klee,False,Almond milk,2.498,0.202,0.053,2.65,-0.129,via-verde|fairtrade|eu-organic
31,"Latte Macchiato, lait d'avoine, Le Klee",Latte Macchiato Via Verde Le Klee,2.7,0.251,2.82,0.123,Latte Macchiato,Le Klee,False,Oat milk,2.498,0.202,0.039,2.60,-0.129,via-verde|fairtrade|eu-organic|eu-organic
32,"Latte Macchiato, lait de soja, Le Klee",Latte Macchiato Via Verde Le Klee,2.7,0.422,2.99,0.293,Latte Macchiato,Le Klee,False,Soya milk,2.498,0.202,0.057,2.65,-0.129,via-verde|fairtrade|eu-organic
33,"Latte Macchiato, sans-lactose, Le Klee",Latte Macchiato Via Verde Le Klee,2.7,0.374,2.95,0.245,Latte Macchiato,Le Klee,False,Cow milk,2.498,0.202,0.052,2.65,-0.129,via-verde|fairtrade|eu-organic
34,"Macchiato, Compass Machine",Macchiato Via Verde Compass Machine,2.2,0.248,2.32,0.120,Macchiato,Compass Machine,False,Cow milk,2.035,0.165,0.039,2.10,-0.129,via-verde|fairtrade|eu-organic
35,"Mocaccino Blue Planet, Dallmayr",Mocaccino Blue Planet Dallmayr,1.8,0.456,1.99,0.193,Mocaccino,Dallmayr,False,Cow milk,1.665,0.135,0.046,1.75,-0.262,blue-planet|fairtrade|eu-organic|rainforest-al...
36,"Mocaccino Via Verde, Dallmayr",Mocaccino Via Verde Dallmayr,1.7,0.413,1.98,0.284,Mocaccino,Dallmayr,False,Cow milk,1.573,0.127,0.056,1.65,-0.129,via-verde|fairtrade|eu-organic|rainforest-alli...
37,"Renversé, Compass Machine",Renversé Via Verde Compass Machine,2.2,0.248,2.32,0.120,Renversé,Compass Machine,False,Cow milk,2.035,0.165,0.039,2.10,-0.129,via-verde|fairtrade|eu-organic
38,"Renversé, Le Klee",Renversé Via Verde Le Klee,2.7,0.374,2.95,0.245,Renversé,Le Klee,False,Cow milk,2.498,0.202,0.052,2.65,-0.129,via-verde|fairtrade|eu-organic
39,"Renversé, lait d'amande, Le Klee",Renversé Via Verde Le Klee,2.7,0.384,2.96,0.255,Renversé,Le Klee,False,Almond milk,2.498,0.202,0.053,2.65,-0.129,via-verde|fairtrade|eu-organic
40,"Renversé, lait d'avoine, Le Klee",Renversé Via Verde Le Klee,2.7,0.251,2.82,0.123,Renversé,Le Klee,False,Oat milk,2.498,0.202,0.039,2.60,-0.129,via-verde|fairtrade|eu-organic|eu-organic
41,"Renversé, lait de soja, Le Klee",Renversé Via Verde Le Klee,2.7,0.422,2.99,0.293,Renversé,Le Klee,False,Soya milk,2.498,0.202,0.057,2.65,-0.129,via-verde|fairtrade|eu-organic
42,"Renversé, sans-lactose, Le Klee",Renversé Via Verde Le Klee,2.7,0.374,2.95,0.245,Renversé,Le Klee,False,Cow milk,2.498,0.202,0.052,2.65,-0.129,via-verde|fairtrade|eu-organic
43,"Ristretto, Compass Machine",Ristretto Via Verde Compass Machine,1.5,0.194,1.57,0.065,Ristretto,Compass Machine,False,none,1.388,0.112,0.033,1.45,-0.129,via-verde|fairtrade|eu-organic
44,"Ristretto, Le Klee",Ristretto Via Verde Le Klee,1.6,0.194,1.67,0.065,Ristretto,Le Klee,False,none,1.480,0.120,0.033,1.55,-0.129,via-verde|fairtrade|eu-organic

In [4]:

duplicate_rows = df_impact_data.groupby(by=["Beverage ID", "Ingredient", "Impact Category", "Stage", "Indicator"]).filter(lambda x: len(x) >= 2)
duplicate_rows = duplicate_rows.sort_values(by=["Beverage ID", "Ingredient", "Impact Category", "Stage", "Indicator"])
duplicate_rows.to_csv('duplicate_rows.csv',index=False)

In [5]:
duplicate_rows

,Beverage ID,Ingredient,Stage,Impact Category,Indicator,Unit,Monetary Value,Value,References
7244,"Café Macchiato Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,8.715723e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7245,"Café Macchiato Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000100,9.245213e-07,"Road; transport, freight, lorry with refrigera..."
7270,"Café Macchiato Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,8.715723e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7271,"Café Macchiato Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000100,9.245213e-07,"Road; transport, freight, lorry with refrigera..."
7296,"Cappuccino Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.030040e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7297,"Cappuccino Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000118,1.092616e-06,"Road; transport, freight, lorry with refrigera..."
7322,"Cappuccino Vanille Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.901612e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7323,"Cappuccino Vanille Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000217,2.017137e-06,"Road; transport, freight, lorry with refrigera..."
7348,"Cappuccino Vanille Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.901612e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7349,"Cappuccino Vanille Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000217,2.017137e-06,"Road; transport, freight, lorry with refrigera..."
7374,"Cappuccino Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.030040e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7375,"Cappuccino Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000118,1.092616e-06,"Road; transport, freight, lorry with refrigera..."
7400,"Cappuccino, Compass Machine",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.030040e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7401,"Cappuccino, Compass Machine",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000118,1.092616e-06,"Road; transport, freight, lorry with refrigera..."
7426,"Cappuccino, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,2.907981e-05,"Road; transport, freight, light commercial veh..."
7427,"Cappuccino, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.001520,1.411996e-05,"Road; transport, freight, lorry with refrigera..."
7506,"Cappuccino, sans-lactose, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,2.907981e-05,"Road; transport, freight, light commercial veh..."
7507,"Cappuccino, sans-lactose, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.001520,1.411996e-05,"Road; transport, freight, lorry with refrigera..."
7550,"Chocolait, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.267742e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7551,"Chocolait, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000145,1.344758e-06,"Road; transport, freight, lorry with refrigera..."
7594,"Espresso Macchiato Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,7.923385e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7595,"Espresso Macchiato Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000090,8.404739e-07,"Road; transport, freight, lorry with refrigera..."
7620,"Espresso Macchiato Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,7.923385e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7621,"Espresso Macchiato Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000090,8.404739e-07,"Road; transport, freight, lorry with refrigera..."
7646,"Frappé Vanille, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,3.169354e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7647,"Frappé Vanille, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000362,3.361896e-06,"Road; transport, freight, lorry with refrigera..."
7672,"Latte Macchiato Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.505443e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7673,"Latte Macchiato Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000172,1.596900e-06,"Road; transport, freight, lorry with refrigera..."
7698,"Latte Macchiato Vanille Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,2.060080e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7699,"Latte Macchiato Vanille Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000235,2.185232e-06,"Road; transport, freight, lorry with refrigera..."
7724,"Latte Macchiato Vanille Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,2.060080e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7725,"Latte Macchiato Vanille Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000235,2.185232e-06,"Road; transport, freight, lorry with refrigera..."
7750,"Latte Macchiato Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,1.505443e-06,"Road; transport, freight, lorry 3.5-7.5 metric..."
7751,"Latte Macchiato Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000172,1.596900e-06,"Road; transport, freight, lorry with refrigera..."
7776,"Latte Macchiato, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,3.634976e-05,"Road; transport, freight, light commercial veh..."
7777,"Latte Macchiato, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.001900,1.764995e-05,"Road; transport, freight, lorry with refrigera..."
7856,"Latte Macchiato, sans-lactose, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,3.634976e-05,"Road; transport, freight, light commercial veh..."
7857,"Latte Macchiato, sans-lactose, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.001900,1.764995e-05,"Road; transport, freight, lorry with refrigera..."
7882,"Macchiato, Compass Machine",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,8.715723e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7883,"Macchiato, Compass Machine",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000100,9.245213e-07,"Road; transport, freight, lorry with refrigera..."
7926,"Mocaccino Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,8.715723e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7927,"Mocaccino Blue Planet, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000100,9.245213e-07,"Road; transport, freight, lorry with refrigera..."
7970,"Mocaccino Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,8.715723e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7971,"Mocaccino Via Verde, Dallmayr",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000100,9.245213e-07,"Road; transport, freight, lorry with refrigera..."
7996,"Renversé, Compass Machine",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,8.715723e-07,"Road; transport, freight, lorry 3.5-7.5 metric..."
7997,"Renversé, Compass Machine",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.000100,9.245213e-07,"Road; transport, freight, lorry with refrigera..."
8022,"Renversé, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,3.634976e-05,"Road; transport, freight, light commercial veh..."
8023,"Renversé, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.001900,1.764995e-05,"Road; transport, freight, lorry with refrigera..."
8102,"Renversé, sans-lactose, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM10 eq,0.000000,3.634976e-05,"Road; transport, freight, light commercial veh..."
8103,"Renversé, sans-lactose, Le Klee",Cow milk,Transport,Environment,Fine particulate matter formation,kg PM2.5 eq,0.001900,1.764995e-05,"Road; transport, freight, lorry with refrigera..."

In [6]:
def get_indicator_values(row):

    # # Find matches where df_impact_description['Indicator'] is contained in row['Indicator']
    # matched_rows = df_impact_description[
    #     df_impact_description['Indicator'].apply(lambda x: x in row['Indicator'])
    # ]
    
    # if matched_rows.empty:
    #     impact_definition = None
    #     monetisation_method = None
    # else:
    #     # Select the most specific match (longest string in df_impact_description['Indicator'])
    #     impact_definition = matched_rows.loc[matched_rows['Indicator'].str.len().idxmax(), 'Indicator definition']
    #     monetisation_method = matched_rows.loc[matched_rows['Indicator'].str.len().idxmax(), 'Monetisation method']
    
    return {
        'indicators': row['Indicator'],
        'unit': row['Unit'],
        'impactValue': row['Value'], 
        'costValue': row['Monetary Value'], 
        # 'impactDefinition': impact_definition,
        # 'monetisationMethod': monetisation_method,
        'reference': None if pd.isna(row['References']) else row['References']
    }
    
def process_group(x):
    try:
        return {
            'stage': x.iloc[0]['Stage'],
            'ingredient': x.iloc[0]['Ingredient'],
            'impactCategory': x.iloc[0]['Impact Category'],
            'impactValue': x['Value'].sum(),   # Sum impact values
            'costValue': x['Monetary Value'].sum(),   # Sum cost values
            'details': x.apply(get_indicator_values, axis=1).tolist()
        }
    except Exception as e:
        print("Error during process_group:", e)
        print(x)
        return {}
        
def calculate_impacts(group):
    # Group by stage and impact-category
    list = []
    grouped_impacts = None
    try:
        grouped_impacts = group.groupby(['Ingredient','Stage', 'Impact Category']).apply(process_group).reset_index(drop=True)
        list = grouped_impacts.tolist()
    except Exception as e:
        print("Error during calculation:", e)
        return None


    return list

In [7]:
# Delete everything inside ./results
results_dir = './results'
for filename in os.listdir(results_dir):
    file_path = os.path.join(results_dir, filename)
    try:
        if os.path.isfile(file_path) or os.path.islink(file_path):
            os.unlink(file_path)
        elif os.path.isdir(file_path):
            shutil.rmtree(file_path)
    except Exception as e:
        print(f'Failed to delete {file_path}. Reason: {e}')

In [8]:
# Transform the data
import re


formatted_data = []

i = 0;

# milk_beverage_lists = ['Cappuccino',"Chocolait","Latte Macchiato","Macchiato","Mocaccino", 'Renversé']

        
for _, beverage in df_beverage_list.iterrows():
    beverage_id = beverage['Beverage ID']
    retail_name = beverage['Retail name']

    # all_removals = labels_list + ['décaféiné', "lait d'amande", "lait d'avoine", "lait de soja", "sans-lactose"]

    # recipe_id_pattern = r'(' + '|'.join(map(re.escape, all_removals)) + r')'
    # recipe_id = re.sub(recipe_id_pattern, '', retail_name, flags=re.IGNORECASE).replace(',','').strip()
    recipe_id = beverage['Beverage-type']
    # sale_point_id = sale_point_mapping[beverage['Salepoint']]
    # is_decaf = 'décaféiné' in beverage['Retail name'].lower()
    is_decaf = beverage['Deca']
    # has_milk = any(x in beverage['Retail name'] for x in milk_beverage_lists)

    # Determine the type of milk, if present
    # milk_types = {'lait d\'amande': 'Almond', 'lait d\'avoine': 'Oat', 'lait de soja': 'Soy', 'sans-lactose': 'Lactose-Free'}
    # milk_type = None
    # for key, value in milk_types.items():
    #     if key in beverage['Retail name'].lower():
    #         milk_type = value
    #         break
    # milk_type = milk_type if milk_type else 'Dairy' if any(x in beverage['Retail name'].lower() for x in ['milk', 'latte', 'cappuccino', 'renversé']) else None
        
    milk_type = beverage['Milk Type']
    has_milk = milk_type != 'none'

    definition_row = df_coffee_description[df_coffee_description['Recipe'] == recipe_id]
    definition = definition_row['Definition'].iloc[0] if not definition_row.empty else ""


    impact_rows = df_impact_data[df_impact_data['Beverage ID'] == beverage_id]
    # print(impact_rows)
    ingredient_list = impact_rows['Ingredient'].unique().tolist()

    if impact_rows.empty:
        print(f"No impact data found for {beverage_id}")

    grouped_impacts = calculate_impacts(impact_rows)

    path_impacts = './results/impacts/'+beverage_id.lower().replace(' ','_').replace(',','')+'.json'
    print(path_impacts)
    os.makedirs(os.path.dirname(path_impacts), exist_ok=True)
    with open(path_impacts, 'w', encoding='utf-8') as f:
        json.dump(grouped_impacts, f, indent=4, ensure_ascii=False)



    formatted_data.append({
        'serveId': beverage_id,
        'recipeId': recipe_id,
        'retailName': retail_name,
        'retailPrice': beverage['Retail price'],
        'hiddenCost': beverage['Hidden Costs'],
        'truePrice': beverage['True Price'],
        'labels': beverage['Labels'],
        "priceWithoutTax": beverage["Price Excluding Tax"],
        'valueAddedTax': beverage["Value Added Tax"],
        'smartValueAddedTax': beverage["Smart Value Added Tax"],
        'smartPricingRounded': beverage["Smart Pricing rounded"],
        "offsetting": beverage["Offsetting"],
        'isDecaf': is_decaf,
        'hasMilk': has_milk,
        'milkType': milk_type,
        'coffeeDetails': definition, 

    })

# Create the formatted DataFrame
formatted_df = pd.DataFrame(formatted_data)

# Save to CSV
output_path = './results/coffee_data.csv'
formatted_df.to_csv(output_path, index=False)



print(f"Formatted data saved to {output_path}")

./results/impacts/café_blue_planet_dallmayr.json
./results/impacts/café_macchiato_blue_planet_dallmayr.json
./results/impacts/café_macchiato_via_verde_dallmayr.json
./results/impacts/café_via_verde_dallmayr.json
./results/impacts/café_compass_machine.json
./results/impacts/café_le_klee.json
./results/impacts/cappuccino_blue_planet_dallmayr.json
./results/impacts/cappuccino_vanille_blue_planet_dallmayr.json
./results/impacts/cappuccino_vanille_via_verde_dallmayr.json
./results/impacts/cappuccino_via_verde_dallmayr.json
./results/impacts/cappuccino_compass_machine.json
./results/impacts/cappuccino_le_klee.json
./results/impacts/cappuccino_lait_d'amande_le_klee.json
./results/impacts/cappuccino_lait_d'avoine_le_klee.json
./results/impacts/cappuccino_lait_de_soja_le_klee.json
./results/impacts/cappuccino_sans-lactose_le_klee.json
./results/impacts/chocolait_dallmayr.json
./results/impacts/chocolat_dallmayr.json
./results/impacts/espresso_blue_planet_dallmayr.json

./results/impacts/espresso_macchiato_blue_planet_dallmayr.json
./results/impacts/espresso_macchiato_via_verde_dallmayr.json
./results/impacts/espresso_via_verde_dallmayr.json
./results/impacts/espresso_compass_machine.json
./results/impacts/espresso_le_klee.json
./results/impacts/frappé_vanille_dallmayr.json
./results/impacts/latte_macchiato_blue_planet_dallmayr.json
./results/impacts/latte_macchiato_vanille_blue_planet_dallmayr.json
./results/impacts/latte_macchiato_vanille_via_verde_dallmayr.json
./results/impacts/latte_macchiato_via_verde_dallmayr.json
./results/impacts/latte_macchiato_le_klee.json
./results/impacts/latte_macchiato_lait_d'amande_le_klee.json
./results/impacts/latte_macchiato_lait_d'avoine_le_klee.json
./results/impacts/latte_macchiato_lait_de_soja_le_klee.json
./results/impacts/latte_macchiato_sans-lactose_le_klee.json
./results/impacts/macchiato_compass_machine.json
./results/impacts/mocaccino_blue_planet_dallmayr.json
./results/impacts/mocaccino_via_verde_dallmayr.json

./results/impacts/renversé_compass_machine.json
./results/impacts/renversé_le_klee.json
./results/impacts/renversé_lait_d'amande_le_klee.json
./results/impacts/renversé_lait_d'avoine_le_klee.json
./results/impacts/renversé_lait_de_soja_le_klee.json
./results/impacts/renversé_sans-lactose_le_klee.json
./results/impacts/ristretto_compass_machine.json
./results/impacts/ristretto_le_klee.json
Formatted data saved to ./results/coffee_data.csv

In [9]:

list_sugars = ["Swiss sugar default","Swiss sugar low","Swiss sugar moderate","Swiss sugar high"]

for sugar in list_sugars:
    sugar_rows = df_sugar_data[df_sugar_data['Beverage ID'] == sugar]
    print(sugar_rows)

    grouped_impacts = calculate_impacts(sugar_rows)

    path_impacts = './results/sugar/'+sugar.lower().replace(' ','_').replace(',','')+'.json'
    os.makedirs(os.path.dirname(path_impacts), exist_ok=True)
    with open(path_impacts, 'w', encoding='utf-8') as f:
        json.dump(grouped_impacts, f, indent=4, ensure_ascii=False)

             Beverage ID      Country Ingredient Labels        Stage  \
0    Swiss sugar default  Switzerland  Sugarbeet   none   Production
1    Swiss sugar default  Switzerland  Sugarbeet   none   Production
2    Swiss sugar default  Switzerland  Sugarbeet   none   Production
3    Swiss sugar default  Switzerland  Sugarbeet   none   Production
4    Swiss sugar default  Switzerland  Sugarbeet   none   Production
..                   ...          ...        ...    ...          ...
189  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
190  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
191  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
192  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption
193  Swiss sugar default  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  Value  \
0       Environment  Fine particulate matter formation  kg PM2.5 eq    0.0
1       Environment           Fossil resource scarcity    kg oil eq    0.0
2       Environment             Freshwater ecotoxicity   kg 1,4-DCB    0.0
3       Environment          Freshwater eutrophication      kg P eq    0.0
4       Environment                     Global warming    kg CO2 eq    0.0
..              ...                                ...          ...    ...
189          Health                     Pyraclostrobin        mg/kg    0.0
190          Health                       Saflufenacil        mg/kg    0.0
191          Health                       Tebufenozide        mg/kg    0.0
192          Health                      Teflubenzuron        mg/kg    0.0
193          Health                   Trinexapac-Ethyl        mg/kg    0.0

     Monetary Value  ...     Salepoint   Deca Milk Type  Price Excluding Tax  \
0               0.0  ...  Rolex Centre  False      none                    0
1               0.0  ...  Rolex Centre  False      none                    0
2               0.0  ...  Rolex Centre  False      none                    0
3               0.0  ...  Rolex Centre  False      none                    0
4               0.0  ...  Rolex Centre  False      none                    0
..              ...  ...           ...    ...       ...                  ...
189             0.0  ...  Rolex Centre  False      none                    0
190             0.0  ...  Rolex Centre  False      none                    0
191             0.0  ...  Rolex Centre  False      none                    0
192             0.0  ...  Rolex Centre  False      none                    0
193             0.0  ...  Rolex Centre  False      none                    0

    Value Added Tax  Smart Value Added Tax Smart Pricing  \
0                 0                  0.026             0
1                 0                  0.026             0
2                 0                  0.026             0
3                 0                  0.026             0
4                 0                  0.026             0
..              ...                    ...           ...
189               0                  0.026             0
190               0                  0.026             0
191               0                  0.026             0
192               0                  0.026             0
193               0                  0.026             0

    Smart Pricing rounded  Value Unit  \
0                       0  USD2023/kg
1                       0  USD2023/kg
2                       0  USD2023/kg
3                       0  USD2023/kg
4                       0  USD2023/kg
..                    ...         ...
189                     0  USD2023/mg
190                     0  USD2023/mg
191                     0  USD2023/mg
192                     0  USD2023/mg
193                     0  USD2023/mg

                                            References
0    Sugar beet {CH}| production | Cut-off, S - Cop...
1    Sugar beet {CH}| production | Cut-off, S - Cop...
2    Sugar beet {CH}| production | Cut-off, S - Cop...
3    Sugar beet {CH}| production | Cut-off, S - Cop...
4    Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
189  Food and Agriculture Organisation, World Healt...
190  Food and Agriculture Organisation, World Healt...
191  Food and Agriculture Organisation, World Healt...
192  Food and Agriculture Organisation, World Healt...
193  Food and Agriculture Organisation, World Healt...

[194 rows x 28 columns]
         Beverage ID      Country Ingredient Labels        Stage  \
388  Swiss sugar low  Switzerland  Sugarbeet   none   Production
389  Swiss sugar low  Switzerland  Sugarbeet   none   Production
390  Swiss sugar low  Switzerland  Sugarbeet   none   Production
391  Swiss sugar low  Switzerland  Sugarbeet   none   Production
392  Swiss sugar low  Switzerland  Sugarbeet   none   Production
..               ...          ...        ...    ...          ...
577  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
578  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
579  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
580  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption
581  Swiss sugar low  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  \
388     Environment  Fine particulate matter formation  kg PM2.5 eq
389     Environment           Fossil resource scarcity    kg oil eq
390     Environment             Freshwater ecotoxicity   kg 1,4-DCB
391     Environment          Freshwater eutrophication      kg P eq
392     Environment                     Global warming    kg CO2 eq
..              ...                                ...          ...
577          Health                     Pyraclostrobin        mg/kg
578          Health                       Saflufenacil        mg/kg
579          Health                       Tebufenozide        mg/kg
580          Health                      Teflubenzuron        mg/kg
581          Health                   Trinexapac-Ethyl        mg/kg

            Value  Monetary Value  ...     Salepoint   Deca Milk Type  \
388  8.193605e-07    8.822059e-05  ...  Rolex Centre  False      none
389  4.492133e-05    2.375131e-05  ...  Rolex Centre  False      none
390  5.255285e-06    2.518892e-07  ...  Rolex Centre  False      none
391  9.091564e-08    2.184047e-05  ...  Rolex Centre  False      none
392  3.811263e-04    7.140582e-05  ...  Rolex Centre  False      none
..            ...             ...  ...           ...    ...       ...
577  1.200000e-04    1.156332e-06  ...  Rolex Centre  False      none
578  4.500000e-05    0.000000e+00  ...  Rolex Centre  False      none
579  1.500000e-03    8.603664e-06  ...  Rolex Centre  False      none
580  1.500000e-05    1.479830e-06  ...  Rolex Centre  False      none
581  7.500000e-04    0.000000e+00  ...  Rolex Centre  False      none

     Price Excluding Tax Value Added Tax  Smart Value Added Tax Smart Pricing  \
388                    0               0               0.026133             0
389                    0               0               0.026133             0
390                    0               0               0.026133             0
391                    0               0               0.026133             0
392                    0               0               0.026133             0
..                   ...             ...                    ...           ...
577                    0               0               0.026133             0
578                    0               0               0.026133             0
579                    0               0               0.026133             0
580                    0               0               0.026133             0
581                    0               0               0.026133             0

    Smart Pricing rounded  Value Unit  \
388                     0  USD2023/kg
389                     0  USD2023/kg
390                     0  USD2023/kg
391                     0  USD2023/kg
392                     0  USD2023/kg
..                    ...         ...
577                     0  USD2023/mg
578                     0  USD2023/mg
579                     0  USD2023/mg
580                     0  USD2023/mg
581                     0  USD2023/mg

                                            References
388  Sugar beet {CH}| production | Cut-off, S - Cop...
389  Sugar beet {CH}| production | Cut-off, S - Cop...
390  Sugar beet {CH}| production | Cut-off, S - Cop...
391  Sugar beet {CH}| production | Cut-off, S - Cop...
392  Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
577  Food and Agriculture Organisation, World Healt...
578  Food and Agriculture Organisation, World Healt...
579  Food and Agriculture Organisation, World Healt...
580  Food and Agriculture Organisation, World Healt...
581  Food and Agriculture Organisation, World Healt...

[194 rows x 28 columns]
              Beverage ID      Country Ingredient Labels        Stage  \
582  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
583  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
584  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
585  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
586  Swiss sugar moderate  Switzerland  Sugarbeet   none   Production
..                    ...          ...        ...    ...          ...
771  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
772  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
773  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
774  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption
775  Swiss sugar moderate  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  \
582     Environment  Fine particulate matter formation  kg PM2.5 eq
583     Environment           Fossil resource scarcity    kg oil eq
584     Environment             Freshwater ecotoxicity   kg 1,4-DCB
585     Environment          Freshwater eutrophication      kg P eq
586     Environment                     Global warming    kg CO2 eq
..              ...                                ...          ...
771          Health                     Pyraclostrobin        mg/kg
772          Health                       Saflufenacil        mg/kg
773          Health                       Tebufenozide        mg/kg
774          Health                      Teflubenzuron        mg/kg
775          Health                   Trinexapac-Ethyl        mg/kg

            Value  Monetary Value  ...     Salepoint   Deca Milk Type  \
582  1.638721e-06    1.764412e-04  ...  Rolex Centre  False      none
583  8.984266e-05    4.750262e-05  ...  Rolex Centre  False      none
584  1.051057e-05    5.037783e-07  ...  Rolex Centre  False      none
585  1.818313e-07    4.368094e-05  ...  Rolex Centre  False      none
586  7.622526e-04    1.428116e-04  ...  Rolex Centre  False      none
..            ...             ...  ...           ...    ...       ...
771  2.400000e-04    2.312665e-06  ...  Rolex Centre  False      none
772  9.000000e-05    0.000000e+00  ...  Rolex Centre  False      none
773  3.000000e-03    1.720733e-05  ...  Rolex Centre  False      none
774  3.000000e-05    2.959660e-06  ...  Rolex Centre  False      none
775  1.500000e-03    0.000000e+00  ...  Rolex Centre  False      none

     Price Excluding Tax Value Added Tax  Smart Value Added Tax Smart Pricing  \
582                    0               0               0.026267             0
583                    0               0               0.026267             0
584                    0               0               0.026267             0
585                    0               0               0.026267             0
586                    0               0               0.026267             0
..                   ...             ...                    ...           ...
771                    0               0               0.026267             0
772                    0               0               0.026267             0
773                    0               0               0.026267             0
774                    0               0               0.026267             0
775                    0               0               0.026267             0

    Smart Pricing rounded  Value Unit  \
582                     0  USD2023/kg
583                     0  USD2023/kg
584                     0  USD2023/kg
585                     0  USD2023/kg
586                     0  USD2023/kg
..                    ...         ...
771                     0  USD2023/mg
772                     0  USD2023/mg
773                     0  USD2023/mg
774                     0  USD2023/mg
775                     0  USD2023/mg

                                            References
582  Sugar beet {CH}| production | Cut-off, S - Cop...
583  Sugar beet {CH}| production | Cut-off, S - Cop...
584  Sugar beet {CH}| production | Cut-off, S - Cop...
585  Sugar beet {CH}| production | Cut-off, S - Cop...
586  Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
771  Food and Agriculture Organisation, World Healt...
772  Food and Agriculture Organisation, World Healt...
773  Food and Agriculture Organisation, World Healt...
774  Food and Agriculture Organisation, World Healt...
775  Food and Agriculture Organisation, World Healt...

[194 rows x 28 columns]
          Beverage ID      Country Ingredient Labels        Stage  \
194  Swiss sugar high  Switzerland  Sugarbeet   none   Production
195  Swiss sugar high  Switzerland  Sugarbeet   none   Production
196  Swiss sugar high  Switzerland  Sugarbeet   none   Production
197  Swiss sugar high  Switzerland  Sugarbeet   none   Production
198  Swiss sugar high  Switzerland  Sugarbeet   none   Production
..                ...          ...        ...    ...          ...
383  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
384  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
385  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
386  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption
387  Swiss sugar high  Switzerland  Sugarbeet   none  Consumption

    Impact Category                          Indicator         Unit  \
194     Environment  Fine particulate matter formation  kg PM2.5 eq
195     Environment           Fossil resource scarcity    kg oil eq
196     Environment             Freshwater ecotoxicity   kg 1,4-DCB
197     Environment          Freshwater eutrophication      kg P eq
198     Environment                     Global warming    kg CO2 eq
..              ...                                ...          ...
383          Health                     Pyraclostrobin        mg/kg
384          Health                       Saflufenacil        mg/kg
385          Health                       Tebufenozide        mg/kg
386          Health                      Teflubenzuron        mg/kg
387          Health                   Trinexapac-Ethyl        mg/kg

            Value  Monetary Value  ...     Salepoint   Deca Milk Type  \
194  2.458082e-06    2.646618e-04  ...  Rolex Centre  False      none
195  1.347640e-04    7.125393e-05  ...  Rolex Centre  False      none
196  1.576586e-05    7.556675e-07  ...  Rolex Centre  False      none
197  2.727469e-07    6.552142e-05  ...  Rolex Centre  False      none
198  1.143379e-03    2.142175e-04  ...  Rolex Centre  False      none
..            ...             ...  ...           ...    ...       ...
383  3.600000e-04    3.468997e-06  ...  Rolex Centre  False      none
384  1.350000e-04    0.000000e+00  ...  Rolex Centre  False      none
385  4.500000e-03    2.581099e-05  ...  Rolex Centre  False      none
386  4.500000e-05    4.439491e-06  ...  Rolex Centre  False      none
387  2.250000e-03    0.000000e+00  ...  Rolex Centre  False      none

     Price Excluding Tax Value Added Tax  Smart Value Added Tax Smart Pricing  \
194                    0               0                 0.0264             0
195                    0               0                 0.0264             0
196                    0               0                 0.0264             0
197                    0               0                 0.0264             0
198                    0               0                 0.0264             0
..                   ...             ...                    ...           ...
383                    0               0                 0.0264             0
384                    0               0                 0.0264             0
385                    0               0                 0.0264             0
386                    0               0                 0.0264             0
387                    0               0                 0.0264             0

    Smart Pricing rounded  Value Unit  \
194                     0  USD2023/kg
195                     0  USD2023/kg
196                     0  USD2023/kg
197                     0  USD2023/kg
198                     0  USD2023/kg
..                    ...         ...
383                     0  USD2023/mg
384                     0  USD2023/mg
385                     0  USD2023/mg
386                     0  USD2023/mg
387                     0  USD2023/mg

                                            References
194  Sugar beet {CH}| production | Cut-off, S - Cop...
195  Sugar beet {CH}| production | Cut-off, S - Cop...
196  Sugar beet {CH}| production | Cut-off, S - Cop...
197  Sugar beet {CH}| production | Cut-off, S - Cop...
198  Sugar beet {CH}| production | Cut-off, S - Cop...
..                                                 ...
383  Food and Agriculture Organisation, World Healt...
384  Food and Agriculture Organisation, World Healt...
385  Food and Agriculture Organisation, World Healt...
386  Food and Agriculture Organisation, World Healt...
387  Food and Agriculture Organisation, World Healt...

[194 rows x 28 columns]

In [10]:
output_path= "./results/impacts_definitions.csv"
df_impact_description.to_csv(output_path, index=False)

In [11]:
source_dir = './results/'
destination_dir = '../public/data/'

# Clean the destination directory
if os.path.exists(destination_dir):
    shutil.rmtree(destination_dir)

# Copy the contents of the source directory to the destination directory
shutil.copytree(source_dir, destination_dir)

print(f"Contents of {source_dir} copied to {destination_dir}")

Contents of ./results/ copied to ../public/data/